---
version: "3.8"
services:
  redis:
    healthcheck:
      test: "redis-cli ping"
      interval: "1s"
      timeout: "1s"
      retries: 10
    image: "redis/redis-stack-server:latest"
    ports:
    - "6379:6379"
    - "8001:8001"
