---
name: "Deploy Tag"
"on":
  create:
    tags:
    - "*"
jobs:
  deploy:
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    env:
      GH_TOKEN: "${{ secrets.GH_TOKEN }}"
    steps:
    - uses: "actions/checkout@v5"
    - name: "Set up JDK 21"
      uses: "actions/setup-java@v5"
      with:
        distribution: "zulu"
        java-version: "21"
        java-package: "jdk"
        cache: "maven"
    - name: "Setup node"
      uses: "actions/setup-node@v6"
      with:
        node-version: 20
        cache: "yarn"
        cache-dependency-path: "ui/app/yarn.lock"
    - name: "Set up Maven"
      uses: "stCarolas/setup-maven@v5"
      with:
        maven-version: "3.9.10"
    - run: "npm set \"//npm.pkg.github.com/:_authToken=$GH_TOKEN\""
    - run: "node --version"
    - run: "npm --version"
    - run: "mvn --version"
    - run: "yarn --version"
    - run: "corepack enable"
    - run: "corepack prepare yarn@stable --activate"
    - run: "yarn set version stable"
    - run: "yarn --version"
    - run: "git fetch --prune --unshallow --tags"
    - run: "make -C ui/app install test buildDev"
    - run: "make 'M=mvn -s settings.xml -T 1C' fmtCheck"
    - run: "make 'M=mvn -s settings.xml -T 1C' deploy"
    - run: "echo $GH_TOKEN | docker login ghcr.io -u USERNAME --password-stdin"
    - run: "make M='mvn -s settings.xml -T 1C -Pdocker-push' validate"
    - name: "Release"
      uses: "softprops/action-gh-release@v2"
      with:
        generate_release_notes: "true"
        make_latest: "true"
        token: "${{ secrets.GH_TOKEN }}"
